### ISSUE TITLE
Frozen clock bug

### ISSUE THREAD

**Issue by thanelmas** [vamartid/Minesweeper#10]
You can start a game with the timer stuck at 0.
Step1: Press "New game"
Step2: Triple click any game (ex "Easy").

I tried this on Windows using the "Minesweeper.exe"

**Comment by vamartid** [comment]
thanks! we are looking into it.

**Comment by vamartid** [comment]
I think the issue was happening because we didn't disable the buttons which add a new view,
after we were using them once.
So the user was adding more than one view
Check the latest changes at [here](https://github.com/vamartid/Minesweeper/tree/builds/_latest-Releases) and infor this issue if it is Fixed.
