### ISSUE TITLE
mines are generated outside the playing field

### ISSUE THREAD

**Issue by RunningDroid** [vamartid/Minesweeper#4]
Visible off the lower right corner in this image
![screenshot_2016-10-06-19-10-24](https://cloud.githubusercontent.com/assets/486393/19174775/71702c56-8bff-11e6-9510-2f968378143a.png)
And off the center of the right side in this image
![screenshot_2016-10-06-19-12-40](https://cloud.githubusercontent.com/assets/486393/19174781/77529b36-8bff-11e6-8993-af94f99200f7.png)

**Comment by Dostoi** [comment]
I'm having the same issue with the f-droid version

**Comment by rigopoui** [comment]
The mine field is generally bigger than the phone screen on the medium and hard difficulties.

Try pinching to zoom in and out, or flicking the screen to see the rest of it.

**Comment by rigopoui** [comment]
Could you confirm that your psoblem was solved so I can close this?

**Comment by RunningDroid** [comment]
Yeah, that was my issue.

**Comment by Dostoi** [comment]
It would be better for the user to start the game with the whole map being shown and let him zoom in after

**Comment by rigopoui** [comment]
I am implementing a kind of solution to show the player that the playing field is bigger than the screen. Just a simple zoom animation when the game starts, that takes you from seeing the whole field, to the default zoom level. 

I wouldn't like to start the game completely unzoomed because at higher difficulties, on mobile phones the cells would become too small to press easily.
